name: Straznik Rynku

on:
  schedule:
    # Uruchamiaj w 15. i 45. minucie każdej godziny
    - cron: '15,45 * * * *'
  workflow_dispatch: # Pozwala uruchomić ręcznie przyciskiem

jobs:
  uruchom-bota:
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz kod
        uses: actions/checkout@v3

      - name: Zainstaluj Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Zainstaluj biblioteki
        run: pip install -r requirements.txt

      - name: Uruchom Straznika
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python straznik_cloud.py
